### ISSUE TITLE
Thanks for the plugin. 

### ISSUE THREAD

**Issue by Twoods1984** [stefancandrea/OctoPrint-Thingiverse#10]
Hey, seen you closed any issues still open due to not supporting the plugin anymore. It has now gotten even hard to do iframes even if the site is blocking it due to new security implementations Google is making. 

With that note if there is a big enough interest I can make a plugin like this using the API as you mentioned. Just not sure if it's still useful to anyone but thanks for all the work you put into this plugin!

**Comment by stefancandrea** [comment]
Thanks @Twoods1984 for all the support, and sorry I could not solve the iframe problem... this would be much easy for all of us.

I think it will be interest on the plugin with the API support.
At least I will install it 👍 

Thanks again, good luck.
