### ISSUE TITLE
Repeated "Update available" notice in OctoPrint

### ISSUE THREAD

**Issue by dxgldotorg** [stefancandrea/OctoPrint-Thingiverse#9]
OctoPrint keeps saying version 1.0.0 is available, and even attempting to manually install the 1.0.0 release doesn't make the notice go away.

**Comment by wvoigt** [comment]
And in my case, it says version 0.1.0 is installed.  So is this possibly a mismatched version number somewhere?
I deleted and reinstalled, and the new version still says 0.1.0.

**Comment by dxgldotorg** [comment]
Perhaps the author forgot to set the version number correctly in the metadata?

**Comment by stefancandrea** [comment]
Hello.

I made a new release. I hope this helps.

https://github.com/stefancandrea/OctoPrint-Thingiverse/releases/tag/1.1.0
